import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Gzip / Brotli compression on all responses
  compress: true,

  // Remove the X-Powered-By: Next.js header (minor security + perf)
  poweredByHeader: false,

  // Serve modern image formats (AVIF → WebP → original)
  images: {
    formats: ["image/avif", "image/webp"],
    // Allow the logo to be auto-optimised from /public
    localPatterns: [{ pathname: "/**" }],
    // Aggressively cache optimised images (31 days)
    minimumCacheTTL: 60 * 60 * 24 * 31,
  },

  // Cache-control headers for static assets
  async headers() {
    return [
      {
        // JS / CSS chunks generated by Next.js — immutable (they have content hashes)
        source: "/_next/static/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable",
          },
        ],
      },
      {
        // Public folder assets (logo, favicons, SVGs, …)
        source: "/:path((?!_next).*\\.(?:png|jpe?g|gif|webp|avif|svg|ico|woff2?|ttf|otf|pdf))$",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=86400, stale-while-revalidate=604800",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
